@extends('frontend.layouts.web')
@section('content')

@include('frontend.components.loader')
@include('frontend.components.scrollup')
@include('frontend.components.header')
@include('frontend.website.slider.slider')
@include('frontend.website.service.service')
@include('frontend.website.about.about')
@include('frontend.website.department.department')
@include('frontend.website.featured.featured')
@include('frontend.website.brand.brand')
@include('frontend.website.team.team')
@include('frontend.website.schedule.schedule')
@include('frontend.website.progress.progress')
@include('frontend.website.shop.shop')
@include('frontend.website.testimonial.testimonial')
@include('frontend.website.blog.blog')
@include('frontend.website.call.call')
@include('frontend.components.footer')
    
@endsection